version: '3'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@mysql:3306
      MYSQL_ROOT_PASSWORD: 'root'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    links:
      - mysql
  mysql:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
