default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
development:
  <<: *default
  database: sample_dev

test:
  <<: *default
  database: sample_test

production:
  <<: *default
  database: sample_prod
